[package]
name = "ergo-supervisor"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
ergo-adapter = { path = "../adapter" }
ergo-runtime = { path = "../runtime" }

serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"